enum MenuState { home, favourite, message, profile }

enum Status { LOADING, COMPLETED, ERROR }

enum Category {
  JACKETS, SHIRTS, T_SHIRTS, TRACK_PANTS, TROUSERS, JEANS,
  TOPS, KURTAS, PALAZZOS, SKIRTS, NONE
}

enum CustomColor {
  RED, BLUE, GREEN, YELLOW, WHITE, PINK, BLACK, GREY, ORANGE, DARK_BLUE, ROSE_WHITE, BROWN, MUSTARD, CREAM, MAROON, NAVY, DARK_GREY, LIGHT_BLUE, OLIVE, TEAL, LAVENDER, WINE, KHAAKI;
}
